config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users do
    resources :questions
    resources :results
  end

  get 'results', to: 'results', controller: 'questions'
  get 'generate_questions', to: 'generate_questions', controller: 'questions'
  
  root to: 'questions#generate_questions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true

  def self.get_questions(myuser)
    @myuser = myuser
    Question.all.sample(5).each {|q| myuser.questions.create(q.slice('ask', 'answer', 'answers')) } if myuser.questions.empty?
  end

  def self.get_question(myuser)
    Question.where(user_id: myuser.id, user_answer: nil).take
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions

  attr_accessor :a, :check_questions, :all_questions
  #Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.get_questions(myuser)
    @myuser = myuser
    #@myuser.all_questions = Question.all.to_a.sample(5)
    #Question.create(@myuser.all_questions.attributes.slice('ask', 'answer', 'answers' ))
    Question.all.sample(5).each {|q| myuser.questions.create(q.slice('ask', 'answer', 'answers')) }
    @myuser.all_questions = Question.where(user_id: myuser.id).to_a
    @myuser.check_questions = @myuser.all_questions.clone
  end

  def self.get_question
    @myuser.a = @myuser.all_questions.pop
  end

  #def self.check_answer
  #  @myuser.a.answer
  #end

  #def self.update_answer
  #  @myuser.check_questions.each { |q| q.update(score: "true") if q.id == @myuser.a.id }
  #end

  #def self.record_user_answer(score_answer)
  #  @myuser.check_questions.each { |q| q.user_answer = score_answer if q.id == @myuser.a.id }
  #end

  def self.last_question?
    @myuser.all_questions.empty?
  end

  def self.correct_result(myuser)
    #myuser.update(score_correct: @myuser.check_questions.select{|a| a.score == "true"}.size)
  end

  def self.incorrect_result(myuser)
    #myuser.update(score_incorrect: @myuser.check_questions.select{|b| b.score == "false"}.size)
  end

  def self.get_answers
    @myuser.check_questions
  end

  def self.user_answers
    @myuser.check_questions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:new]

  def generate_questions
    Question.get_questions(current_user)
    render 'questions/start.html.slim'
  end

  def new
    @question = Question.get_question(current_user)
    @answers = @question.answers.split(':').sample(5) if !@question.nil?
    if @question.nil?
      current_user.update(score_correct: current_user.questions.select{|a| a.score == "true"}.size, score_incorrect: current_user.questions.select{|b| b.score == "false"}.size)
      render 'result.html.slim'
    end
  end

  def update
    @question = Question.find(params[:question_id])
    score_answer = params[:question][:score]
    @question.update(score: 'true') if score_answer == @question.answer
    @question.update(user_answer: score_answer)
    redirect_to action: "new"
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:score)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= link_to "Log Out", destroy_user_session_path, method: :delete if user_signed_in?%>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_question.html.slim
= form_for @question, remote: true, html: {id: "form-#{@question.id}"} do |f|

  p #{@question.ask}

  p
  = f.radio_button :score, 21
  = f.label :score, "#{@answer1}", value: "#{@answer1}"

  p
  = f.radio_button :score, 22
  = f.label :score, "#{@answer2}", value: "#{@answer2}"

  p
  = f.radio_button :score, 23
  = f.label :score, "#{@answer3}", value: "#{@answer3}"

  p
  = f.radio_button :score, 24
  = f.label :score, "#{@answer4}", value: "#{@answer4}"

  p
  = f.radio_button :score, 25
  = f.label :score, "#{@answer5}", value: "#{@answer5}"

  p

  = f.submit "Next Question"

app/views/questions/new.html.slim
body oncontextmenu="return false"
= form_for @question, url: new_user_question_path(question_id: @question.id), html: { class: "main-window" } do |f|

  p #{@question.ask}
  
  - @answers.each do |answer|

     p
     = f.radio_button :score, answer, required: true
     = f.label :score, answer

  p
  = f.submit "#{ @question.empty ? 'Finish' : 'Next Question'}"

app/views/questions/result.html.slim
table
  thead
    tr
      th Question
      th id='center' Your answer
      th id='center' Correct answer
      th id='center' Result
  tbody
    - current_user.questions.each do |a|
      tr
        td = a.ask
        td id='center' = a.user_answer
        td id='center' = a.answer
        td id='center' = a.user_answer == a.answer ? 'Correct' : 'Incorrect'

p 
b Count of correct answers: #{current_user.score_correct}
p 
b Count of incorrect answers: #{current_user.score_incorrect}

p id='result' #{current_user.score_correct > '3' ? 'Pass' : 'Failed'}

app/views/questions/results.html.slim
table
  thead
    tr
      th User Mail
      th Correct Answers
      th Incorrect answers
      th Result
  tbody
    - User.all.each do |user|
      tr
        td = user.email
        td = user.score_correct
        td = user.score_incorrect
        td = #{User.find(user.id).score_correct > 3 ? Pass : Failed}

app/views/questions/start.html.slim
p= link_to "Start my exam", new_user_question_path(current_user)
p= link_to "Get results of all users", results_path

app/views/questions/update.js.erb
$('#form-' + <%= @question.id %>).html( '<%= j render @question %>' );